// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "FeelinIt",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "FeelinIt",
            targets: ["AppModule"],
            bundleIdentifier: "com.lms.FeelinIt",
            teamIdentifier: "HN837W3RNR",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .map),
            accentColor: .presetColor(.pink),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "FeelinIt uses your front camera to detect hand gestures for emotion regulation."),
                .microphone(purposeString: "FeelinIt uses your microphone to detect breathing patterns for emotion regulation.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageModes: [.v6]
)
